apiVersion: v1
kind: Service
metadata:
  name: front-service-svc
  namespace: factory
spec:
  type: NodePort
  selector:
    app: front-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000