server:
  port: 9399
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: data-service
          uri: http://localhost:9099
          predicates:
            - Path=/data/**
          filters:
            - RewritePath=/data/(?<path>.*), /$\{path}
        - id: data-service-documentation
          uri: http://localhost:9099
          predicates:
            - Path=/docs/data
          filters:
            - RewritePath=/docs/data, /v3/api-docs
        - id: users-service-documentation
          uri: http://localhost:9299
          predicates:
            - Path=/docs/users
          filters:
            - RewritePath=/docs/users, /v3/api-docs

config:
  createAccount:
    enabled: true
    fromPath: '/users/users'
    toPath: '/users'
    targetService: 'http://127.0.0.1:9299'
  accessTokenAcquirablePaths:
    - '/login'
    - '/login/**'
  publicPaths:
    - '/login'
    - '/refresh'
    - '/users/users'
    - '/login/**'
    - '/refresh/**'
    - '/docs/data'
    - '/docs/users'

clients:
  user:
    url: http://localhost:9299
    userDetailsPath: '/users/{userName}'

jwt:
  jwtSecret: abc123sajdfisadnfuisndufinhdssvfmdsaiofnhuad9fhuew0nio9adnhfi9oeqfoadnvfopgkmpwomgi0mgisofmgifsogmfdi0ognm53490hg3u9nh3nhe9tighkjr23423432rt2g54y45h45yh4egergh35gerg35h4rth
  jwtAccessTokenExpirationInMs: 600000
  jwtRefreshTokenExpirationInMs: 1200000

login:
  maxAttempts: 10
  renewInMinutes: 1