server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: data-service
          uri: http://data-service-svc:8080
          predicates:
            - Path=/data/**
          filters:
            - RewritePath=/data/(?<path>.*), /$\{path}
        - id: data-service-documentation
          uri: http://data-service-svc:8080
          predicates:
            - Path=/docs/data
          filters:
            - RewritePath=/docs/data, /v3/api-docs
        - id: users-service-documentation
          uri: http://users-service-svc:8080
          predicates:
            - Path=/docs/users
          filters:
            - RewritePath=/docs/users, /v3/api-docs

config:
  createAccount:
    enabled: true
    fromPath: '/users/users'
    toPath: '/users'
    targetService: 'http://users-service-svc:8080'
  accessTokenAcquirablePaths:
    - '/login'
    - '/login/**'
  publicPaths:
    - '/login'
    - '/refresh'
    - '/users/users'
    - '/login/**'
    - '/refresh/**'
    - '/docs/data'
    - '/docs/users'

clients:
  user:
    url: http://users-service-svc:8080
    userDetailsPath: '/users/{userName}'

jwt:
  jwtSecret: ${JWT_SECRET}
  jwtAccessTokenExpirationInMs: 600000
  jwtRefreshTokenExpirationInMs: 1200000

login:
  maxAttempts: 10
  renewInMinutes: 1